import React from 'react';
import { Scale, ShieldCheck, ShieldAlert, AlertTriangle, CheckCircle2, Lock, FileCode, Check } from 'lucide-react';
import { DashboardSummary } from '../types';

interface PolicyEngineViewProps {
  summary: DashboardSummary | null;
}

export const PolicyEngineView: React.FC<PolicyEngineViewProps> = ({ summary }) => {
  const policyRules = [
    {
      id: 'POL-001',
      name: 'Maximum Discount Cap',
      desc: 'Enforces hard ceiling on customer discounts to prevent revenue leakage.',
      threshold: '≤ 20.0%',
      type: 'Financial Safety',
      status: 'Enforcing',
      violationsCaught: 1,
    },
    {
      id: 'POL-002',
      name: 'Maximum Transaction Ceiling',
      desc: 'Restricts single automated recovery link value to pre-approved corporate limit.',
      threshold: '≤ ₹100,000.00',
      type: 'Exposure Cap',
      status: 'Enforcing',
      violationsCaught: 0,
    },
    {
      id: 'POL-003',
      name: '24-Hour Outreach Frequency Limit',
      desc: 'Prevents customer spam by allowing at most 1 automated offer per 24 hours per customer.',
      threshold: '≤ 1 outreach / 24h',
      type: 'Customer Protection',
      status: 'Enforcing',
      violationsCaught: 1,
    },
    {
      id: 'POL-004',
      name: 'Minimum Order Value (MOV) Floor',
      desc: 'Prevents recovery actions for transactions below operational break-even threshold.',
      threshold: '≥ ₹200.00',
      type: 'Unit Economics',
      status: 'Enforcing',
      violationsCaught: 0,
    },
    {
      id: 'POL-005',
      name: 'Offer Expiration Bounds',
      desc: 'Enforces strictly expiring payment links to maintain urgency and limit floating liability.',
      threshold: '≤ 72 Hours',
      type: 'Liability Control',
      status: 'Enforcing',
      violationsCaught: 0,
    },
    {
      id: 'POL-006',
      name: 'Strict Opportunity-Action Type Mapping',
      desc: 'Ensures AI can only propose actions semantically valid for the detected event type.',
      threshold: 'Schema Validated',
      type: 'Deterministic Mapping',
      status: 'Enforcing',
      violationsCaught: 0,
    },
    {
      id: 'POL-007',
      name: 'Adversarial Prompt & Injection Defense',
      desc: 'Sanitizes and blocks any prompt override, instruction tampering, or prompt leak attempt.',
      threshold: 'Zero Tolerance',
      type: 'AI Security',
      status: 'Enforcing',
      violationsCaught: 0,
    },
    {
      id: 'POL-008',
      name: 'Customer Risk Tier & Blacklist Enforcement',
      desc: 'Instantly blocks offers to accounts flagged for fraud or chargeback abuse.',
      threshold: 'Tier A/B only',
      type: 'Fraud Defense',
      status: 'Enforcing',
      violationsCaught: 0,
    },
    {
      id: 'POL-009',
      name: 'Idempotency Key Collision Check',
      desc: 'Guarantees that no Razorpay payment link or charge is executed more than once.',
      threshold: 'Unique SHA key',
      type: 'Data Integrity',
      status: 'Enforcing',
      violationsCaught: 0,
    },
    {
      id: 'POL-010',
      name: 'Cryptographic SHA-256 Audit Trail Chaining',
      desc: 'Guarantees that every policy evaluation verdict is permanently sealed in the audit ledger.',
      threshold: 'SHA-256 Hash Chain',
      type: 'Compliance',
      status: 'Enforcing',
      violationsCaught: 0,
    },
  ];

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="panel-card p-6 bg-gradient-to-r from-[#111318] to-[#161a24] border border-sky-500/20">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <Scale className="w-5 h-5 text-sky-400" />
              <h2 className="text-base font-bold text-white tracking-tight">
                Deterministic Policy & Safety Guardrails Catalog
              </h2>
            </div>
            <p className="text-xs text-slate-400 mt-1 max-w-2xl">
              All AI agent proposals generated by Gemini 2.0 Flash are strictly evaluated against 10 zero-trust deterministic safety policies before any Razorpay API calls are permitted.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <div className="p-3 rounded-lg bg-[#0e1014] border border-[#23252b] text-center">
              <span className="text-[10px] text-slate-400 uppercase font-bold block">Engine State</span>
              <span className="text-xs font-bold text-emerald-400 font-tabular flex items-center gap-1 mt-0.5">
                <CheckCircle2 className="w-3.5 h-3.5" /> 100% ENFORCING
              </span>
            </div>
            <div className="p-3 rounded-lg bg-[#0e1014] border border-[#23252b] text-center">
              <span className="text-[10px] text-slate-400 uppercase font-bold block">Active Rules</span>
              <span className="text-xs font-bold text-sky-300 font-tabular mt-0.5 block">
                10 Rules
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Rules Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {policyRules.map((rule) => (
          <div
            key={rule.id}
            className="panel-card p-5 hover:border-sky-500/40 transition-all flex flex-col justify-between"
          >
            <div>
              <div className="flex items-start justify-between gap-2 mb-2">
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-mono font-bold bg-[#1b1f28] text-sky-400 border border-sky-500/30 px-2 py-0.5 rounded">
                    {rule.id}
                  </span>
                  <h3 className="text-xs font-bold text-slate-100">{rule.name}</h3>
                </div>
                <span className="status-chip status-chip-approved text-[9px]">
                  {rule.status}
                </span>
              </div>
              <p className="text-xs text-slate-400 leading-relaxed mb-3">
                {rule.desc}
              </p>
            </div>

            <div className="pt-3 border-t border-[#23252b] flex items-center justify-between text-[11px] font-tabular">
              <div className="flex items-center gap-1 text-slate-400">
                <span>Enforced Bound:</span>
                <strong className="text-slate-200">{rule.threshold}</strong>
              </div>
              <span className="text-[10px] text-slate-500 font-medium">
                {rule.type}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
